services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - server
      - ai-agent

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env

  ai-agent:
    build:
      context: ./ai-agent
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./ai-agent:/app
    env_file:
      - ./ai-agent/.env
