FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN cd server && npm install

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_API_BASE_URL
ARG VITE_AI_AGENT_URL
ARG VITE_APP_VERSION=dev

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_AI_AGENT_URL=$VITE_AI_AGENT_URL
ENV VITE_APP_VERSION=$VITE_APP_VERSION

RUN npm run build

EXPOSE 8080

CMD ["node", "server/src/index.js"]
